baseurl: /sorteador

theme: jekyll-theme-hacker

title: Concursos e Processos Seletivos &mdash; Editais ATAc/EEL/USP
description: Sorteador de pontos para provas did√°ticas e escritas

email: luizeleno@usp.br
name: Prof. Dr. Luiz T. F. Eleno
dados: "http://www.demar.eel.usp.br/docentes/luiz-tadeu-fernandes-eleno.html"
